baseurl = "https://www.mattallford.com"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Matt Allford"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
disqusShortname = "mattallford"
googleAnalytics = "UA-163892167-2"

[Params]
  homeTitle = " " # Set a different text for the header on the home page
  #subtitle = "Byte sized snippets"
  mainSections = ["post","posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = false
  showRelatedPosts = true
  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
 [[Params.bigimg]]
  src = "img/headerbackground-copy.png"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Matthew Allford"
  website = "www.mattallford.com"
#  email = "youremail@domain.com"
#  facebook = "username"
  github = "mattallford"
#  gitlab = "username"
#  bitbucket = "username"
  twitter = "mattallford"
#  reddit = "username"
  linkedin = "mattallford"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  instagram = "username"
  youtube = "channel/UCWPrPzVnLa9ma7axTJgUX0Q"
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  vk = "username"
#  paypal = "username"
#  telegram = "username"
#  500px = "username"
#  codepen = "username"
  mastodon = "mastodon.social/@mattallford"
#  kaggle = "username"
#  weibo = "username"
#  slack = "username"

[[menu.main]]
    name = "Content Portfolio"
    url = "/content-portfolio/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

#[[menu.main]]
#    parent = "sponsors"
#    name = "Vembu"
#    url = "sponsors/vembu"
#    weight = 1